language: ruby
rvm:
  - 2.7.1
cache:
  - bundler
  - yarn
services:
  - postgresql
before_install:
  - nvm install stable
  - nvm use stable
before_script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - bundle exec rails db:create
  - bundle exec rails db:migrate
script:
  - bundle exec rails spec
